### ISSUE TITLE
Guzzle Client should be injected into Pixers\SalesManagoAPI\Client

### ISSUE THREAD

**Issue by orfin** [pixers/salesmanago-api#2]
Currently it's no way to inject globally used Guzzle Client instance as SM Client initiates it in the constructor.

We should allow to set it (setter injection or constructor injection?)

```
$client = new Client($clientId, $endpoint, $apiSecret, $apiKey);
$client->setGuzzleClient($guzzleClient);
```

and than, instead of using:

```
$this->guzzleClient->request
```

we should:

```
$this->getGuzzleClient()->request
```

getGuzzleClient can lazy-create GuzzleClient if it's not set.

cc @ikselll what do you think?

**Comment by ikselll** [comment]
Good idea @orfin, will code it :)
