### ISSUE TITLE
test hasContact when contact does not exist

### ISSUE THREAD

**Issue by lury** [pixers/salesmanago-api#6]
Hi,

Have you tested ContactService->has() with non existing contact?

In my case it fails due to Guzzle\json_decode error when response body is "False".

When you override it to global \json_decode() it fails in the next line assuming that response body has a success field, but response is basically only this "False" value.

**Comment by ikselll** [comment]
Thanks for reporting this :) I'll check it and fix it.

**Comment by lury** [comment]
while test case will be usefull i think there's something wrong with my code causing it not to return correct results, because json response from SM API is as follows:

```
{"success":true,"message":[],"result":false,"contactId":null}
```

so your code should be able to convert it to json and find "success" field.

Maybe you could provide some config sample? I've noticed that when i use http://www.salesmanago.pl as an endpoint it works, but returns an error mentioned above (i've tried it also with SM Events - same result, so it's not an issue with "False" response) but when i use www.salesmanago.pl without protocol, it returns Guzzle error with "http://http:www.salesmanago.pl" as a problematic url.

When i run simple requests with SM sample code - do_post_request() function, everything works fine so all my credentials, endpoints, contacts etc. are correct.

**Comment by ikselll** [comment]
EndPoint should be `http://XXX.salesmanago.pl/api/` where `XXX` is the server that is listed in SM panel, ex. `www`.

**Comment by lury** [comment]
yup, and it is "www.salesmanago.pl" so i use http://www.salesmanago.pl

![screen shot 2016-08-30 at 08 26 31](https://cloud.githubusercontent.com/assets/457190/18078394/9363bad0-6e8b-11e6-9b41-bcda729d2791.jpg)

**Comment by ikselll** [comment]
So if with endPoint = `http://www.salesmanago.pl/api/` there is error I'll fix it soon ;)

**Comment by lury** [comment]
`/api/` !? omg, that was the issue - i've assumed that you're adding this somewhere on the way since this part never changes and in the panel you don't have this '/api/' part at the end...

My assumption came from SM sample code, where this '/api/' part was concatenated in do_post_request call.

Now it's working even for non existing contacts.

Still, test should be there ;)

**Comment by ikselll** [comment]
Yes. We dedided that building endpoint string is ... point less :) Since it never changes so why it can't be in config?
I'm glad I could help :)
