### ISSUE TITLE
method name in Email service

### ISSUE THREAD

**Issue by lury** [pixers/salesmanago-api#7]
Hi,

don't you think that EmailService->create should be rather called "send" or "addEmailToQueue" or anything that wouldn't require reading your class code to be sure what it actually does? :)

"send" is the API method but to be exact it does not send the email - it adds this mailing to the queue and it will be send according to "date" field in payload.

also example payloads in function descriptions would be nice.

**Comment by orfin** [comment]
Thanks, we will consider renaming this method. Can you please submit PR? I think "send" will be fine.

BTW. there is a way to use it without actually adding mail to the queue - there's a 'hidden way' that allows you to send email instantly from this method :-)

**Comment by lury** [comment]
PR created with immediate set in create wrapper function.

I've decided not to change this method name but added signature change because account owner field is required to send email and you assume that it exists in $data which forced me to make few tries before making it work. This is a bit weird since in API docs this field (user) is not marked as required.
